[package]
name = "starknet_accounts_cairo1"
version = "0.1.0"
description = "Workshop to learn the basics of Cairo."

[[target.starknet-contract]]
name = "contracts"

[dependencies]
core = { path = "/home/felix/software/blockchain/starknet/cairo/corelib" }